<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dtos\CreateProductDto.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="HtmlSanitizer" Version="9.2.1039" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Adaptor\ECommerce.Adaptor.csproj" />
    <ProjectReference Include="..\ECommerce.Domain\ECommerce.Domain.csproj" />
    <ProjectReference Include="..\ECommerce.Repository\ECommerce.Repository.csproj" />
  </ItemGroup>

</Project>
